### ISSUE TITLE
프로젝트 초기 세팅

### ISSUE THREAD

**Issue by 1022gusl** [part2-1/fandom-k#2]
프로젝트 초기 세팅을 위해 추가할 내용 공유하기

**Comment by y00n1verse** [comment]
- 간단하게나마 폴더 구조를 만들어봤는데 팀미팅 후 반영하면 될 것 같습니다. (폴더만 참고 바랍니다) 
- 그리고 jsx가 포함된 파일의 확장자명은 .jsx로 통일하는 게 좋을 것 같습니다. 
- PR 올리실 때도 내용은 스프린트 미션 때와 같이 마크다운 문법을 지키면 더 깔끔하게 보실 수 있을 것 같습니다. 

![폴더구조](https://github.com/user-attachments/assets/cf4185ec-c949-4865-91e7-6c82e95196fb)
